import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Scrolling from "./lenis";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kevin Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* PERUBAHAN ADA DI SINI */}
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-slate-900 min-h-screen`}
      >
        
        {/* BUNGKUS DI SINI (Lenis Scrolling) */}
        <Scrolling>
           {children}
        </Scrolling>

      </body>
    </html>
  );
}